CREATE TABLE product (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL
);

INSERT INTO product (name, price) VALUES ('Laptop', 1200.00);
INSERT INTO product (name, price) VALUES ('Mouse', 25.50);
INSERT INTO product (name, price) VALUES ('Keyboard', 80.00);
INSERT INTO product (name, price) VALUES ('Monitor', 300.00);
INSERT INTO product (name, price) VALUES ('USB Cable', 15.00);
