CREATE TABLE review (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment    VARCHAR(1000),
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES product (id)
);
