package com.example;

import java.util.List;

import com.example.model.Product;

public class Main {
    public static void main(String[] args) {
        // Using the AllArgsConstructor generated by Lombok
        Product myProduct = new Product(101L, "Wireless Mouse", 25.50);

        // Using the Getter generated by Lombok
        System.out.println("Product Name: " + myProduct.getName());
        
        // Testing the Setter
        myProduct.setName("Gaming Mouse");
        System.out.println("Updated Product Name: " + myProduct.getName());


        ProductService service = new ProductService();

        System.out.println("--- Products above $100 ---");
        service.getProductsAbovePrice(100.0)
               .forEach(p -> System.out.println(p.getName() + ": $" + p.getPrice()));

        System.out.println("\n--- All Product Names ---");
        List<String> names = service.getAllProductNames();
        System.out.println(names);
    }
}