package com.example;

import com.example.model.Product;

public class Main {
    public static void main(String[] args) {
        // Using the AllArgsConstructor generated by Lombok
        Product myProduct = new Product(101L, "Wireless Mouse", 25.50);

        // Using the Getter generated by Lombok
        System.out.println("Product Name: " + myProduct.getName());
        
        // Testing the Setter
        myProduct.setName("Gaming Mouse");
        System.out.println("Updated Product Name: " + myProduct.getName());
    }
}